/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a4baea06-2e2e-4828-bbbb-606616d7c6d4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XNq4euvxd",
    "aws_user_pools_web_client_id": "49ljjfn7djklnqt4krvjulbk7l",
    "oauth": {}
};


export default awsmobile;
